/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grupolisp.pokemon.gui;

import grupolisp.pokemon.controller.PokemonManager;
import grupolisp.pokemon.model.bean.Batalla;
import grupolisp.pokemon.model.bean.Entrenador;
import grupolisp.pokemon.model.bean.Pokemon;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author César Olivera
 */
public class BatallaPokemon extends javax.swing.JInternalFrame {

    /**
     * Creates new form BatallaPokemon
     */
    public BatallaPokemon() {
        initComponents();
    }
    
    Entrenador entrenador=new Entrenador();
    Entrenador entrenador_op = null;
    Batalla batalla=new Batalla();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movimientos = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        hpentrenador = new javax.swing.JProgressBar();
        hpentrenadorop = new javax.swing.JProgressBar();
        jSeparator1 = new javax.swing.JSeparator();
        lblopentrenador = new javax.swing.JLabel();
        lblentrenador = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbpokemon = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        pokemon1 = new javax.swing.JLabel();
        pokemon2 = new javax.swing.JLabel();
        pokemonop1 = new javax.swing.JLabel();
        pokemonop2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        movimientospokemon = new javax.swing.JPanel();
        movimiento1 = new javax.swing.JRadioButton();
        movimiento2 = new javax.swing.JRadioButton();
        movimiento4 = new javax.swing.JRadioButton();
        movimiento3 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        movimientoop1 = new javax.swing.JLabel();
        movimientoop2 = new javax.swing.JLabel();
        movimientoop3 = new javax.swing.JLabel();
        movimientoop4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        imgcurrpokemon = new javax.swing.JLabel();
        pokemoncurrent = new javax.swing.JLabel();
        hp = new javax.swing.JLabel();
        ataque = new javax.swing.JLabel();
        defensa = new javax.swing.JLabel();
        velocidad = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        imgcurrpokemonop = new javax.swing.JLabel();
        pokemoncurrentop = new javax.swing.JLabel();
        defensaop = new javax.swing.JLabel();
        hpop = new javax.swing.JLabel();
        velocidadop = new javax.swing.JLabel();
        ataqueop = new javax.swing.JLabel();
        hppokemon1 = new javax.swing.JProgressBar();
        hppokemon2 = new javax.swing.JProgressBar();
        hppokemonop1 = new javax.swing.JProgressBar();
        hppokemonop2 = new javax.swing.JProgressBar();
        Iniciar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("BATALLA POKEMON");

        jButton1.setText("Realizar movimiento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        hpentrenador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hpentrenador.setForeground(new java.awt.Color(102, 255, 102));

        hpentrenadorop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hpentrenadorop.setForeground(new java.awt.Color(102, 255, 102));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblopentrenador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblopentrenador.setText("Nombre de oponente");

        lblentrenador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblentrenador.setText("Nombre de entrenador");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cambiar Pokemon"));

        cmbpokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpokemonActionPerformed(evt);
            }
        });

        jButton2.setText("Cambiar Pokemon");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cmbpokemon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cmbpokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        pokemon1.setText("POKEMON1");

        pokemon2.setText("POKEMON2");

        pokemonop1.setText("POKEMON1");

        pokemonop2.setText("POKEMON2");

        jLabel1.setText("HP");

        jLabel4.setText("HP");

        movimientospokemon.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimientos"));

        movimientos.add(movimiento1);
        movimiento1.setText("Movimiento 1");

        movimientos.add(movimiento2);
        movimiento2.setText("Movimiento 2");

        movimientos.add(movimiento4);
        movimiento4.setText("Movimiento 4");

        movimientos.add(movimiento3);
        movimiento3.setText("Movimiento 3");

        javax.swing.GroupLayout movimientospokemonLayout = new javax.swing.GroupLayout(movimientospokemon);
        movimientospokemon.setLayout(movimientospokemonLayout);
        movimientospokemonLayout.setHorizontalGroup(
            movimientospokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movimientospokemonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movimientospokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movimiento1)
                    .addComponent(movimiento2)
                    .addComponent(movimiento4)
                    .addComponent(movimiento3))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        movimientospokemonLayout.setVerticalGroup(
            movimientospokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movimientospokemonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movimiento1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movimiento2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movimiento3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                .addComponent(movimiento4))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimientos"));

        movimientoop1.setText("Movimiento 1");

        movimientoop2.setText("movimiento 2");

        movimientoop3.setText("Movimiento 3");

        movimientoop4.setText("Movimiento 4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movimientoop2)
                    .addComponent(movimientoop1)
                    .addComponent(movimientoop3)
                    .addComponent(movimientoop4))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(movimientoop1)
                .addGap(13, 13, 13)
                .addComponent(movimientoop2)
                .addGap(18, 18, 18)
                .addComponent(movimientoop3)
                .addGap(11, 11, 11)
                .addComponent(movimientoop4))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Pokemon en batalla"));

        imgcurrpokemon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        pokemoncurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pokemoncurrent.setText("Current Pokemon");

        hp.setText("HP");

        ataque.setText("Ataque");

        defensa.setText("Defensa");

        velocidad.setText("Velocidad");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hp)
                    .addComponent(ataque)
                    .addComponent(defensa)
                    .addComponent(velocidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgcurrpokemon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pokemoncurrent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(imgcurrpokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pokemoncurrent))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ataque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(defensa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(velocidad)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Pokemon en batalla"));

        imgcurrpokemonop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        pokemoncurrentop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pokemoncurrentop.setText("Current Pokemon op");

        defensaop.setText("Defensa");

        hpop.setText("HP");

        velocidadop.setText("Velocidad");

        ataqueop.setText("Ataque");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgcurrpokemonop, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pokemoncurrentop, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hpop)
                    .addComponent(ataqueop)
                    .addComponent(defensaop)
                    .addComponent(velocidadop))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(imgcurrpokemonop, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pokemoncurrentop))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(hpop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ataqueop)
                        .addGap(13, 13, 13)
                        .addComponent(defensaop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(velocidadop)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Iniciar.setText("Empezar Batalla");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblentrenador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hpentrenador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(movimientospokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pokemon1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addComponent(pokemon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(hppokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hppokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(hpentrenadorop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblopentrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pokemonop2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pokemonop1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hppokemonop2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hppokemonop1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Iniciar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblentrenador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblopentrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hpentrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hpentrenadorop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pokemon1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hppokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pokemon2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hppokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movimientospokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pokemonop1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hppokemonop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pokemonop2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hppokemonop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)))
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addComponent(Iniciar, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void actualizarDatosdelLosPokemons() throws SQLException{
        hppokemon1.setMaximum(PokemonManager.queryByNameOfPokemon(pokemon1.getText()).getHp());
        hppokemon2.setMaximum(PokemonManager.queryByNameOfPokemon(pokemon2.getText()).getHp());
        hppokemon1.setValue(entrenador.getPokemonByName(pokemon1.getText()).getHp());
        hppokemon1.setStringPainted(true);
        hppokemon1.setString("HP: "+entrenador.getPokemonByName(pokemon1.getText()).getHp());
        hppokemon2.setValue(entrenador.getPokemonByName(pokemon2.getText()).getHp());
        hppokemon2.setStringPainted(true);
        hppokemon2.setString("HP: "+entrenador.getPokemonByName(pokemon2.getText()).getHp());
        
        hp.setText("HP: "+entrenador.getPokemonByName(pokemoncurrent.getText()).getHp());
        ataque.setText("Ataque: "+entrenador.getPokemonByName(pokemoncurrent.getText()).getAtaque());
        
        
        hppokemonop1.setMaximum(PokemonManager.queryByNameOfPokemon(pokemonop1.getText()).getHp());
        hppokemonop2.setMaximum(PokemonManager.queryByNameOfPokemon(pokemonop2.getText()).getHp());
        hppokemonop1.setValue(entrenador_op.getPokemonByName(pokemonop1.getText()).getHp());
        hppokemonop1.setStringPainted(true);
        hppokemonop1.setString("HP: "+entrenador_op.getPokemonByName(pokemonop1.getText()).getHp());
        hppokemonop2.setValue(entrenador_op.getPokemonByName(pokemonop2.getText()).getHp());
        hppokemonop2.setStringPainted(true);
        hppokemonop2.setString("HP: "+entrenador_op.getPokemonByName(pokemonop2.getText()).getHp());
        
        hpop.setText("HP: "+entrenador_op.getPokemonByName(pokemoncurrentop.getText()).getHp());
        ataqueop.setText("Ataque: "+entrenador_op.getPokemonByName(pokemoncurrentop.getText()).getAtaque());
        
    }
    
    private void cmbpokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpokemonActionPerformed
        
    }//GEN-LAST:event_cmbpokemonActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        batalla.setId(1);
        try {
            //Se prepara al oponente
            entrenador_op=PokemonManager.queryByNameOfEntrenador(lblopentrenador.getText());
            entrenador_op.addPokemon(PokemonManager.queryByNameOfPokemon("Pikachu"));
            batalla.setHp_oponente(PokemonManager.queryByNameOfPokemon("Pikachu").getHp());
            entrenador_op.addPokemon(PokemonManager.queryByNameOfPokemon("Bulbasaur"));
            batalla.setHp_oponente(batalla.getHp_oponente()+PokemonManager.queryByNameOfPokemon("Bulbasaur").getHp());
            entrenador_op.addPokemon(PokemonManager.queryByNameOfPokemon("Charmander"));
            batalla.setHp_oponente(batalla.getHp_oponente()+PokemonManager.queryByNameOfPokemon("Charmander").getHp());
            //Se añade movimientos a cada pokemon (4 por pokemon)
            for(int i=0;i<entrenador_op.getPokemon().size();i++)
                PokemonManager.addMovimientos(entrenador_op.getPokemon().get(i));
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Se prepara el entrenador
        entrenador.setNombre(lblentrenador.getText());
        entrenador.setBatallas_ganadas(0);
        entrenador.setBatallas_perdidas(0);
        entrenador.setRegDate(new Date());
        try {
            PokemonManager.addEntrenador(entrenador);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Pokemon pokemon=PokemonManager.queryByNameOfPokemon(pokemon1.getText());
            entrenador.addPokemon(pokemon);
            batalla.setHp_entrenador(batalla.getHp_entrenador()+pokemon.getHp());
            pokemon=PokemonManager.queryByNameOfPokemon(pokemon2.getText());
            entrenador.addPokemon(pokemon);
            batalla.setHp_entrenador(batalla.getHp_entrenador()+pokemon.getHp());
            pokemon=PokemonManager.queryByNameOfPokemon(pokemoncurrent.getText());
            entrenador.addPokemon(pokemon);
            batalla.setHp_entrenador(batalla.getHp_entrenador()+pokemon.getHp());
            
            //Se añade movimientos a cada pokemon (4 por pokemon)
            for(int i=0;i<entrenador.getPokemon().size();i++){
                PokemonManager.addMovimientos(entrenador.getPokemon().get(i));  
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //LLenar la data de la pantalla
        //Setear datos del entrenador
        //Progress bar (HP) jugador
        hpentrenador.setMaximum(batalla.getHp_entrenador());
        hpentrenador.setValue(batalla.getHp_entrenador());
        hpentrenador.setStringPainted(true);
        hpentrenador.setString("HP: "+batalla.getHp_entrenador());
        
        lblentrenador.setText(entrenador.getNombre());
        pokemon1.setText(entrenador.getPokemon().get(0).getNombre());
        pokemon2.setText(entrenador.getPokemon().get(1).getNombre());
        pokemoncurrent.setText(entrenador.getPokemon().get(2).getNombre());
        
        hppokemon1.setMaximum(entrenador.getPokemonByName(pokemon1.getText()).getHp());
        hppokemon2.setMaximum(entrenador.getPokemonByName(pokemon2.getText()).getHp());
        hppokemon1.setValue(entrenador.getPokemonByName(pokemon1.getText()).getHp());
        hppokemon2.setValue(entrenador.getPokemonByName(pokemon2.getText()).getHp());
        
        ImageIcon icon=new ImageIcon(entrenador.getPokemon().get(2).getImage());
        imgcurrpokemon.setIcon(icon);
        
        
        
        
        //Completar movimientos
        List<Pokemon> listPokemon = entrenador.getPokemon();
        
        movimiento1.setText(listPokemon.get(2).getMovimientos().get(0).getNombre());
        movimiento2.setText(listPokemon.get(2).getMovimientos().get(1).getNombre());
        movimiento3.setText(listPokemon.get(2).getMovimientos().get(2).getNombre());
        movimiento4.setText(listPokemon.get(2).getMovimientos().get(3).getNombre());
        
        //Llenar el combobox
        cmbpokemon.addItem(pokemon1.getText());
        cmbpokemon.addItem(pokemon2.getText());
        
        //Setear datos del entrenador oponente
        //Progress bar (HP) oponente
        hpentrenadorop.setMaximum(batalla.getHp_oponente());
        hpentrenadorop.setValue(batalla.getHp_oponente());
        hpentrenadorop.setStringPainted(true);
        hpentrenadorop.setString("HP: "+batalla.getHp_oponente());
        
        
        lblopentrenador.setText(entrenador_op.getNombre());
        pokemonop1.setText(entrenador_op.getPokemon().get(0).getNombre());
        pokemonop2.setText(entrenador_op.getPokemon().get(1).getNombre());
        pokemoncurrentop.setText(entrenador_op.getPokemon().get(2).getNombre());
        
        hppokemonop1.setMaximum(entrenador_op.getPokemonByName(pokemonop1.getText()).getHp());
        hppokemonop2.setMaximum(entrenador_op.getPokemonByName(pokemonop2.getText()).getHp());
        hppokemonop1.setValue(entrenador_op.getPokemonByName(pokemonop1.getText()).getHp());
        hppokemonop2.setValue(entrenador_op.getPokemonByName(pokemonop2.getText()).getHp());
        
        ImageIcon iconop=new ImageIcon(entrenador_op.getPokemon().get(2).getImage());
        imgcurrpokemonop.setIcon(iconop);
        //Completar movimientos
        List<Pokemon> listPokemon_op = entrenador_op.getPokemon();
        
        //Completar datos del pokemon en combate
        hpop.setText(""+entrenador_op.getPokemonByName(pokemoncurrentop.getText()).getHp());
        ataqueop.setText(""+entrenador_op.getPokemonByName(pokemoncurrentop.getText()).getAtaque());
        
        movimientoop1.setText(listPokemon_op.get(2).getMovimientos().get(0).getNombre());
        movimientoop2.setText(listPokemon_op.get(2).getMovimientos().get(1).getNombre());
        movimientoop3.setText(listPokemon_op.get(2).getMovimientos().get(2).getNombre());
        movimientoop4.setText(listPokemon_op.get(2).getMovimientos().get(3).getNombre());
            
        Iniciar.setEnabled(false);
        Iniciar.setText("");
        Iniciar.setBorder(null);
    }//GEN-LAST:event_IniciarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Hacemos el cambio de pokemon
        Pokemon pokemon=null;
        JOptionPane.showMessageDialog(null, "Indice seleccionado "+cmbpokemon.getSelectedIndex());
        switch (cmbpokemon.getSelectedIndex()){
            case 0: 
                    String pokAux1 = "";
                    char str1[]=pokemoncurrent.getText().toCharArray();
                    for(int i=0;i<str1.length;i++)
                        pokAux1+=str1[i];
                    String pokAux2 = "";
                    char str2[]=pokemon1.getText().toCharArray();
                    for(int i=0;i<str2.length;i++)
                        pokAux2+=str2[i];
                    
                    pokemoncurrent.setText(pokAux2);
                    pokemon1.setText(pokAux1);
                    cmbpokemon.removeAllItems();
                    cmbpokemon.addItem(pokAux1);
                    cmbpokemon.addItem(pokemon2.getText());
                    break;
            case 1:
                    String pokAux3 = "";
                    char str3[]=pokemoncurrent.getText().toCharArray();
                    for(int i=0;i<str3.length;i++)
                        pokAux3+=str3[i];
                    String pokAux4 = "";
                    char str4[]=pokemon2.getText().toCharArray();
                    for(int i=0;i<str4.length;i++)
                        pokAux4+=str4[i];
                    
                    pokemoncurrent.setText(pokAux4);
                    pokemon2.setText(pokAux3);
                    
                    cmbpokemon.removeAllItems();
                    cmbpokemon.addItem(pokemon1.getText());
                    cmbpokemon.addItem(pokAux3);
                    break;
        }
        try {
            pokemon=PokemonManager.queryByNameOfPokemon(pokemoncurrent.getText());
            ImageIcon icon=new ImageIcon(pokemon.getImage());
            imgcurrpokemon.setIcon(icon);
            
            Pokemon pokemonAux=null;
            for(int i=0;i<entrenador.getPokemon().size();i++)
                if(entrenador.getPokemon().get(i).getNombre().equals(pokemoncurrent.getText())){
                    //JOptionPane.showMessageDialog(null, "pokemon "+entrenador.getPokemon().get(i).getNombre());
                    pokemonAux = entrenador.getPokemon().get(i);
                } 
                    
            movimiento1.setText(pokemonAux.getMovimientos().get(0).getNombre());
            movimiento2.setText(pokemonAux.getMovimientos().get(1).getNombre());
            movimiento3.setText(pokemonAux.getMovimientos().get(2).getNombre());
            movimiento4.setText(pokemonAux.getMovimientos().get(3).getNombre());
            
            //Actualizo barras de vida
            hppokemon1.setMaximum(PokemonManager.queryByNameOfPokemon(pokemon1.getText()).getHp());
            hppokemon1.setValue(entrenador.getPokemonByName(pokemon1.getText()).getHp());
            hppokemon1.setString("HP: "+entrenador.getPokemonByName(pokemon2.getText()).getHp());
            hppokemon1.setMaximum(PokemonManager.queryByNameOfPokemon(pokemon2.getText()).getHp());
            hppokemon2.setValue(entrenador.getPokemonByName(pokemon2.getText()).getHp());
            hppokemon2.setString("HP: "+entrenador.getPokemonByName(pokemon2.getText()).getHp());
            
            hppokemonop1.setValue(entrenador_op.getPokemonByName(pokemonop1.getText()).getHp());
            hppokemonop1.setString("HP: "+entrenador_op.getPokemonByName(pokemonop1.getText()).getHp());
            hppokemonop2.setValue(entrenador_op.getPokemonByName(pokemonop2.getText()).getHp());
            hppokemonop2.setString("HP: "+entrenador_op.getPokemonByName(pokemonop2.getText()).getHp());
            
        } catch (SQLException ex) {
            Logger.getLogger(BatallaPokemon.class.getName()).log(Level.SEVERE, null, ex);
        }

//        pokemoncurrent.setText(entrenador.getPokemon().get(2).getNombre());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(batalla.getHp_entrenador()!=0 && batalla.getHp_oponente()!=0){
            
            //Se realiza el turno
            //Se busca el indice del pokemon seleccionado
            
            int indexPokemon=0;
            for(int i=0;i<entrenador.getPokemon().size();i++){
                if(entrenador.getPokemon().get(i).getNombre().equals(pokemoncurrent.getText())) indexPokemon=i;
            }
            if(!entrenador.getPokemon().get(indexPokemon).isEn_combate()){
                JOptionPane.showMessageDialog(null, "El pokemon que elegiste esta fuera de combate, por favor elije otro pokemon");
                return;
            }
            //Se busca el indice del movimiento seleccionado
            int indexMovimiento=0;
            if(movimiento1.isSelected())indexMovimiento=0;
            else if(movimiento2.isSelected())indexMovimiento=1;
            else if(movimiento3.isSelected())indexMovimiento=2;
            else if(movimiento4.isSelected())indexMovimiento=3;
            else return;
            PokemonManager.ataquePokemon(batalla,entrenador.getPokemon().get(indexPokemon),indexMovimiento,entrenador_op);
//            //Eliminar pokemones derrotados
//            //La computadora
//            for(int i=0;i<entrenador_op.getPokemon().size();i++){
//                if(entrenador_op.getPokemon().get(i).getHp()<=0)
//                    
//            }
            
            //Progress bar (HP) jugador
            hpentrenador.setValue(batalla.getHp_entrenador());
            hpentrenador.setStringPainted(true);
            hpentrenador.setString("HP: "+batalla.getHp_entrenador());  
            
            //Progress bar (HP) oponente
            hpentrenadorop.setValue(batalla.getHp_oponente());
            hpentrenadorop.setStringPainted(true);
            hpentrenadorop.setString("HP: "+batalla.getHp_oponente());
            
            Pokemon pokAux=entrenador_op.getPokemonByName(pokemoncurrentop.getText());

            if(pokAux.getHp()==0){
                //Verificar si quedan 2 ó 1 pokemon
                Pokemon pokAux1=entrenador_op.getPokemonByName(pokemonop1.getText());
                Pokemon pokAux2=entrenador_op.getPokemonByName(pokemonop2.getText());
                
                if((pokAux2.isEn_combate() && !pokAux1.isEn_combate())||
                   (pokAux1.isEn_combate() && pokAux2.isEn_combate()))
                {
                    //Se realiza el cambio entre el pokemon 2 y el actual
                    String pokAuxStr = "";
                    char str1[]=pokemoncurrentop.getText().toCharArray();
                    for(int i=0;i<str1.length;i++)
                        pokAuxStr+=str1[i];
                    pokemoncurrentop.setText(pokemonop2.getText());
                    pokemonop2.setText(pokAuxStr);
                    
                    ImageIcon iconop = null;
                    try {
                        iconop = new ImageIcon(PokemonManager.queryByNameOfPokemon(pokemoncurrentop.getText()).getImage());
                    } catch (SQLException ex) {
                        Logger.getLogger(BatallaPokemon.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    imgcurrpokemonop.setIcon(iconop);
                    
                    Pokemon pokemonAux= entrenador_op.getPokemonByName(pokemoncurrentop.getText());
                    movimientoop1.setText(pokemonAux.getMovimientos().get(0).getNombre());
                    movimientoop2.setText(pokemonAux.getMovimientos().get(1).getNombre());
                    movimientoop3.setText(pokemonAux.getMovimientos().get(2).getNombre());
                    movimientoop4.setText(pokemonAux.getMovimientos().get(3).getNombre());
                    
                }
                else if(pokAux1!=null){
                    //Se realiza el cambio entre el pokemon 1 y el actual
                }
                else{
                    JOptionPane.showMessageDialog(null, "La batalla ha finalizado. EL ganador fue "+entrenador.getNombre());
                }
                
                
                
                
                String aux=pokemonop2.getText();
                
                pokemonop1.setText(entrenador_op.getPokemon().get(0).getNombre());
                pokemonop2.setText(entrenador_op.getPokemon().get(1).getNombre());
                pokemoncurrentop.setText(entrenador_op.getPokemon().get(2).getNombre());

                ImageIcon iconop=new ImageIcon(entrenador_op.getPokemon().get(2).getImage());
                imgcurrpokemonop.setIcon(iconop);

//                //Completar movimientos
//                List<Pokemon> listPokemon_op = entrenador_op.getPokemon();
//
//                movimientoop1.setText(listPokemon_op.get(2).getMovimientos().get(0).getNombre());
//                movimientoop2.setText(listPokemon_op.get(2).getMovimientos().get(1).getNombre());
//                movimientoop3.setText(listPokemon_op.get(2).getMovimientos().get(2).getNombre());
//                movimientoop4.setText(listPokemon_op.get(2).getMovimientos().get(3).getNombre());
            }
            
            try {
                //Actualizar las barras de vida de los pokemons
                actualizarDatosdelLosPokemons();
            } catch (SQLException ex) {
                Logger.getLogger(BatallaPokemon.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            ImageIcon icon = null;
            try {
                icon = new ImageIcon(PokemonManager.queryByNameOfPokemon(pokemoncurrent.getText()).getImage());
            } catch (SQLException ex) {
                Logger.getLogger(BatallaPokemon.class.getName()).log(Level.SEVERE, null, ex);
            }
            imgcurrpokemon.setIcon(icon);
            Pokemon pokemonAux=entrenador_op.getPokemonByName(pokemoncurrentop.getText());

            movimientoop1.setText(pokemonAux.getMovimientos().get(0).getNombre());
            movimientoop2.setText(pokemonAux.getMovimientos().get(1).getNombre());
            movimientoop3.setText(pokemonAux.getMovimientos().get(2).getNombre());
            movimientoop4.setText(pokemonAux.getMovimientos().get(3).getNombre());
           //hpop.setText(""+entrenador_op.getPokemonByName(pokemoncurrentop.getText()));
           //ataqueop.setText(""+entrenador_op.getPokemonByName(pokemoncurrentop.getText()).getAtaque());
        }
        else{
            if(batalla.getHp_entrenador()<=0)
                JOptionPane.showMessageDialog(null, "Finalizo la batalla. Ganador: "+entrenador_op.getNombre());
            else 
                JOptionPane.showMessageDialog(null, "Finalizo la batalla. Ganador: "+entrenador.getNombre());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Iniciar;
    public javax.swing.JLabel ataque;
    public javax.swing.JLabel ataqueop;
    private javax.swing.JComboBox<String> cmbpokemon;
    public javax.swing.JLabel defensa;
    public javax.swing.JLabel defensaop;
    public javax.swing.JLabel hp;
    public javax.swing.JProgressBar hpentrenador;
    public javax.swing.JProgressBar hpentrenadorop;
    private javax.swing.JLabel hpop;
    public javax.swing.JProgressBar hppokemon1;
    public javax.swing.JProgressBar hppokemon2;
    private javax.swing.JProgressBar hppokemonop1;
    private javax.swing.JProgressBar hppokemonop2;
    public javax.swing.JLabel imgcurrpokemon;
    public javax.swing.JLabel imgcurrpokemonop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblentrenador;
    public javax.swing.JLabel lblopentrenador;
    public javax.swing.JRadioButton movimiento1;
    public javax.swing.JRadioButton movimiento2;
    public javax.swing.JRadioButton movimiento3;
    public javax.swing.JRadioButton movimiento4;
    public javax.swing.JLabel movimientoop1;
    public javax.swing.JLabel movimientoop2;
    public javax.swing.JLabel movimientoop3;
    public javax.swing.JLabel movimientoop4;
    public javax.swing.ButtonGroup movimientos;
    public javax.swing.JPanel movimientospokemon;
    public javax.swing.JLabel pokemon1;
    public javax.swing.JLabel pokemon2;
    public javax.swing.JLabel pokemoncurrent;
    public javax.swing.JLabel pokemoncurrentop;
    public javax.swing.JLabel pokemonop1;
    public javax.swing.JLabel pokemonop2;
    public javax.swing.JLabel velocidad;
    public javax.swing.JLabel velocidadop;
    // End of variables declaration//GEN-END:variables
}
