/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grupolisp.pokemon.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author César Olivera
 */
public class DataGame extends javax.swing.JInternalFrame {

    /**
     * Creates new form DataGame
     */
    public DataGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modobatalla = new javax.swing.ButtonGroup();
        dificultad = new javax.swing.ButtonGroup();
        txtnentrenador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        confirmdatosbatalla = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        modo = new javax.swing.JPanel();
        batalla3x3 = new javax.swing.JRadioButton();
        batalla4x4 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        rbfacil = new javax.swing.JRadioButton();
        rbdificil = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("Datos del jugador");

        txtnentrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnentrenadorActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese su nombre de entrenador pokemon:");

        confirmdatosbatalla.setText("OK");
        confirmdatosbatalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmdatosbatallaActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        modo.setBorder(javax.swing.BorderFactory.createTitledBorder("Modo de Batalla"));

        modobatalla.add(batalla3x3);
        batalla3x3.setSelected(true);
        batalla3x3.setText("Batalla 3 vs 3");

        modobatalla.add(batalla4x4);
        batalla4x4.setText("Batalla 4 vs 4");

        javax.swing.GroupLayout modoLayout = new javax.swing.GroupLayout(modo);
        modo.setLayout(modoLayout);
        modoLayout.setHorizontalGroup(
            modoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(batalla3x3)
                    .addComponent(batalla4x4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        modoLayout.setVerticalGroup(
            modoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(batalla3x3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(batalla4x4))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dificultad"));

        dificultad.add(rbfacil);
        rbfacil.setSelected(true);
        rbfacil.setText("Facil");

        dificultad.add(rbdificil);
        rbdificil.setText("Dificil");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbfacil)
                    .addComponent(rbdificil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbfacil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(rbdificil)
                .addContainerGap())
        );

        jLabel1.setText("POKEMON PRIMERA GENERACIÓN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtnentrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(modo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(360, 360, 360))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(confirmdatosbatalla)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(231, 231, 231))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnentrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(74, 74, 74)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(modo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmdatosbatalla)
                    .addComponent(jButton2))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnentrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnentrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnentrenadorActionPerformed

    private void confirmdatosbatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmdatosbatallaActionPerformed
        // Para el nombre de entrenador pokemon:
        String nombreEntrenador;
        nombreEntrenador = txtnentrenador.getText();

        if(txtnentrenador.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor ingrese su nombre de entrenador pokemon");
            return;
        }
 
        //Para la dificultad del juego
        String dificultad;

        if(rbfacil.isSelected()){
            dificultad="facil";
        }
        else if(rbdificil.isSelected()){
            dificultad="dificil";
        }
        this.dispose();
    }//GEN-LAST:event_confirmdatosbatallaActionPerformed
    public int getModoJuego(){
        int modo=1;
        if(batalla3x3.isSelected()){
            modo= 1;
        }
        else if(batalla4x4.isSelected()){
            modo= 2;
        } 
        return modo;
    }
    public String getNombEntrenador(){
        return txtnentrenador.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton batalla3x3;
    private javax.swing.JRadioButton batalla4x4;
    private javax.swing.JButton confirmdatosbatalla;
    private javax.swing.ButtonGroup dificultad;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel modo;
    private javax.swing.ButtonGroup modobatalla;
    private javax.swing.JRadioButton rbdificil;
    private javax.swing.JRadioButton rbfacil;
    public javax.swing.JTextField txtnentrenador;
    // End of variables declaration//GEN-END:variables
}
