/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grupolisp.pokemon.gui;

import grupolisp.pokemon.controller.PokemonManager;
import grupolisp.pokemon.model.bean.Batalla;
import grupolisp.pokemon.model.bean.Entrenador;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author César Olivera
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modobatalla = new javax.swing.ButtonGroup();
        dificultadgroup = new javax.swing.ButtonGroup();
        escritorio = new javax.swing.JDesktopPane();
        txtnentrenador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        confirmdatosbatalla = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        batalla3x3 = new javax.swing.JRadioButton();
        batalla4x4 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        rbfacil = new javax.swing.JRadioButton();
        rbdificil = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        txtnentrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnentrenadorActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese su nombre de entrenador pokemon:");

        confirmdatosbatalla.setText("OK");
        confirmdatosbatalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmdatosbatallaActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Modo de Batalla"));

        modobatalla.add(batalla3x3);
        batalla3x3.setSelected(true);
        batalla3x3.setText("Batalla 3 vs 3");

        modobatalla.add(batalla4x4);
        batalla4x4.setText("Batalla 4 vs 4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(batalla3x3)
                    .addComponent(batalla4x4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(batalla3x3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(batalla4x4))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dificultad"));

        dificultadgroup.add(rbfacil);
        rbfacil.setSelected(true);
        rbfacil.setText("Facil");

        dificultadgroup.add(rbdificil);
        rbdificil.setText("Dificil");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbfacil)
                    .addComponent(rbdificil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbfacil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(rbdificil)
                .addContainerGap())
        );

        jLabel1.setText("POKEMON PRIMERA GENERACIÓN");

        escritorio.setLayer(txtnentrenador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(confirmdatosbatalla, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(194, 194, 194))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtnentrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmdatosbatalla))
                .addGap(42, 42, 42)
                .addComponent(jButton2)
                .addGap(243, 243, 243))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnentrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(74, 74, 74)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmdatosbatalla)
                    .addComponent(jButton2))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnentrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnentrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnentrenadorActionPerformed

    private void confirmdatosbatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmdatosbatallaActionPerformed
        // Para el nombre de entrenador pokemon:
        String nombreEntrenador;
        nombreEntrenador = txtnentrenador.getText();
        
        if(txtnentrenador.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor ingrese su nombre de entrenador pokemon");
            return;
        }
        //Para el modo de batalla
        int modoBatalla;
        
        if(batalla3x3.isSelected()){
            modoBatalla=1;
        }
        else if(batalla4x4.isSelected()){
            modoBatalla=2;
        }
        //Para la dificultad del juego
        String dificultad;
        
        if(rbfacil.isSelected()){
            dificultad="facil";
        }
        else if(rbdificil.isSelected()){
            dificultad="dificil";
        }
        //Empieza la batalla
        Batalla batalla=new Batalla();
        batalla.setId(1);
        //Se prepara el entrenador
        Entrenador entrenador=new Entrenador();
        entrenador.setNombre(nombreEntrenador);
        entrenador.setBatallas_ganadas(0);
        entrenador.setBatallas_perdidas(0);
        entrenador.setRegDate(new Date());
        try {
            PokemonManager.addEntrenador(entrenador);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Se prepara al oponente
        Entrenador entrenador_op = null;
        try {      
            entrenador_op=PokemonManager.queryByNameOfEntrenador("Equipo Rocket");
            entrenador_op.addPokemon(PokemonManager.queryByNameOfPokemon("Pikachu"));
            batalla.setHp_oponente(PokemonManager.queryByNameOfPokemon("Pikachu").getHp());
            entrenador_op.addPokemon(PokemonManager.queryByNameOfPokemon("Bulbasaur"));
            batalla.setHp_oponente(batalla.getHp_oponente()+PokemonManager.queryByNameOfPokemon("Bulbasaur").getHp());
            entrenador_op.addPokemon(PokemonManager.queryByNameOfPokemon("Charmander"));
            batalla.setHp_oponente(batalla.getHp_oponente()+PokemonManager.queryByNameOfPokemon("Charmander").getHp());
            //Se añade movimientos a cada pokemon (4 por pokemon)
            for(int i=0;i<entrenador_op.getPokemon().size();i++)
                PokemonManager.addMovimientos(entrenador_op.getPokemon().get(i));
            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Código para mostrar los Datos del oponente
        VentanaDatosOp formop = new VentanaDatosOp();
        escritorio.add(formop);//this.setVisible(false);
        formop.show();
        formop.lblnopentrenador.setText(entrenador_op.getNombre());
        formop.lblnumvictorias.setText(""+entrenador_op.getBatallas_ganadas());
        formop.lblnumderrotas.setText(""+entrenador_op.getBatallas_perdidas());
        
        //mostrar pokemons
        ImageIcon icon1=new ImageIcon(entrenador_op.getPokemon().get(0).getImage());
        formop.nombPokemon1.setText(entrenador_op.getPokemon().get(0).getNombre());
        formop.lblpokemon1.setIcon(icon1);
        
        ImageIcon icon2=new ImageIcon(entrenador_op.getPokemon().get(1).getImage());
        formop.nombPokemon2.setText(entrenador_op.getPokemon().get(1).getNombre());
        formop.lblpokemon2.setIcon(icon2);
        
        ImageIcon icon3=new ImageIcon(entrenador_op.getPokemon().get(2).getImage());
        formop.nombPokemon3.setText(entrenador_op.getPokemon().get(2).getNombre());
        formop.lblpokemon3.setIcon(icon3);
        
        //Código para llamar al formulario para elegir los pokemons
//        ElegirPokemons ventanaElegirPokemons = new ElegirPokemons();
//        ventanaElegirPokemons.setVisible(true);
//        ventanaElegirPokemons.lblnentrenador.setText("Bienvenido entrenador "+nombreEntrenador);
        
    }//GEN-LAST:event_confirmdatosbatallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton batalla3x3;
    private javax.swing.JRadioButton batalla4x4;
    private javax.swing.JButton confirmdatosbatalla;
    private javax.swing.ButtonGroup dificultadgroup;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup modobatalla;
    private javax.swing.JRadioButton rbdificil;
    private javax.swing.JRadioButton rbfacil;
    private javax.swing.JTextField txtnentrenador;
    // End of variables declaration//GEN-END:variables
}
